version: '3'
services:
  app:
    build: .
    image: andywuwu/coze2openai:latest
    ports:
      - "3000:3000"
    environment:
      - BOT_ID=${BOT_ID}
      - BOT_CONFIG=${BOT_CONFIG}
      - COZE_API_BASE=${COZE_API_BASE}