name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get release tag
        id: release_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: andywuwu/coze2openai:${{ steps.release_tag.outputs.VERSION }}

      - name: Tag and push latest image
        run: |
          docker pull andywuwu/coze2openai:${{ steps.release_tag.outputs.VERSION }}
          docker tag andywuwu/coze2openai:${{ steps.release_tag.outputs.VERSION }} andywuwu/coze2openai:latest
          docker push andywuwu/coze2openai:latest
